# Generated by Django 5.0.4 on 2024-07-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='music_file_data',
            field=models.BinaryField(null=True),
        ),
    ]
