# Generated by Django 5.0.4 on 2024-07-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_music_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='music_file_data',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
